In [1]:
# prepare data

In [2]:
import pandas as pd
import numpy as np
import glob
import os
from pathlib import Path


start_year = 2017

# adds dir
odds_path = './odds/' 
tml_path = './TML-Database/'
players_atp_path = "./TML-Database/ATP_Database.csv"

In [3]:
excel_files = glob.glob(os.path.join(odds_path, '*.xlsx'))
excel_files =  list(filter(
    lambda f: int(Path(f).stem.strip()) >= start_year,
    excel_files
))
df_list = []

for file in excel_files:
    df = pd.read_excel(file)
    df_list.append(df)

odds_df = pd.concat(df_list, ignore_index=True)
odds_df = odds_df.replace('-', np.nan)
odds_df.sample(8).T

/tmp/ipykernel_268121/3171361819.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  odds_df = odds_df.replace('-', np.nan)

,1903,15774,4663,7493,10578,6032,19079,5551
ATP,49,29,49,23,33,19,47,5
Location,Washington,Paris,Cincinnati,Monte Carlo,Paris,New York,Cincinnati,Cordoba
Tournament,Citi Open,French Open,Western & Southern Financial Group Masters,Monte Carlo Masters,French Open,US Open,Western & Southern Financial Group Masters,Cordoba Open
Date,2018-08-02 00:00:00,2025-05-25 00:00:00,2024-08-15 00:00:00,2022-04-14 00:00:00,2017-06-04 00:00:00,2020-09-02 00:00:00,2021-08-17 00:00:00,2020-02-04 00:00:00
Series,ATP500,Grand Slam,Masters 1000,Masters 1000,Grand Slam,Grand Slam,Masters 1000,ATP250
Court,Outdoor,Outdoor,Outdoor,Outdoor,Outdoor,Outdoor,Outdoor,Outdoor
Surface,Hard,Clay,Hard,Clay,Clay,Hard,Hard,Clay
Round,2nd Round,1st Round,2nd Round,3rd Round,3rd Round,1st Round,1st Round,1st Round
Best of,3.0,5.0,3.0,3.0,5.0,5.0,3.0,3.0
Winner,Zverev A.,Navone M.,Zverev A.,Fritz T.,Monfils G.,De Minaur A.,Mcdonald M.,Taberner C.
Loser,Jaziri M.,Nakashima B.,Khachanov K.,Korda S.,Gasquet R.,Martin A.,Nakashima B.,Verdasco F.
WRank,3.0,97.0,4.0,13.0,16.0,28.0,64.0,198.0
LRank,64.0,32.0,22.0,42.0,25.0,98.0,86.0,49.0
WPts,5665.0,620.0,6995.0,2875.0,2365.0,1485.0,1060.0,252.0
LPts,884.0,1690.0,1880.0,1134.0,1605.0,638.0,893.0,1050.0
W1,6.0,7.0,6.0,7.0,7.0,6.0,7.0,4.0
L1,2.0,6.0,3.0,6.0,6.0,4.0,5.0,6.0
W2,6.0,4.0,6.0,7.0,5.0,6.0,6.0,6.0
L2,1.0,6.0,2.0,5.0,7.0,3.0,2.0,1.0
W3,NaN,6.0,NaN,NaN,4.0,7.0,NaN,6.0
L3,NaN,1.0,NaN,NaN,3.0,5.0,NaN,4.0
W4,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN
L4,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
W5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
L5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wsets,2.0,3.0,2.0,2.0,1.0,3.0,2.0,2.0
Lsets,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
Comment,Completed,Completed,Completed,Completed,Retired,Completed,Completed,Completed
B365W,1.11,1.5,1.25,2.2,1.61,1.06,2.2,2.5
B365L,6.5,2.63,4.0,1.66,2.3,10.0,1.66,1.5
EXW,1.11,NaN,NaN,NaN,1.62,NaN,NaN,NaN
EXL,5.6,NaN,NaN,NaN,2.15,NaN,NaN,NaN
LBW,1.11,NaN,NaN,NaN,1.67,NaN,NaN,NaN
LBL,6.5,NaN,NaN,NaN,2.2,NaN,NaN,NaN
PSW,1.15,1.49,1.25,2.14,1.71,1.06,2.34,2.97
PSL,6.57,2.84,4.4,1.8,2.3,13.07,1.68,1.44
MaxW,1.15,1.5,1.28,2.23,1.75,1.07,2.36,3.0
MaxL,7.0,2.98,4.4,1.82,2.3,13.07,1.78,1.55
AvgW,1.12,1.48,1.25,2.13,1.66,1.05,2.25,2.7
AvgL,6.2,2.69,3.96,1.71,2.21,10.55,1.64,1.46
BFEW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BFEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
odds_df.to_parquet('./ods.parquet')

In [5]:
# odds_df.sample(4).to_string()

In [6]:
csv_files = glob.glob(os.path.join(tml_path, '*.csv'))
csv_files =  sorted(
    filter(lambda f: Path(f).stem.strip().isdigit() and int(Path(f).stem.strip()) >= start_year, csv_files),
    key=lambda f: int(Path(f).stem.strip())
)
df_list = []

for file in csv_files:
    df = pd.read_csv(file)
    df_list.append(df)

tml_df = pd.concat(df_list, ignore_index=True)
tml_df = tml_df.replace('-', np.nan)
tml_df.sample(8).T

,8584,24791,11449,11853,5822,24802,2625,23661
tourney_id,2019-352,2025-7696,2021-321,2021-7480,2018-352,2026-9900,2017-747,2025-314
tourney_name,Paris Masters,Next Gen ATP Finals,Stuttgart,Los Cabos,Paris Masters,United Cup,Beijing,Gstaad
surface,Hard,Hard,Grass,Hard,Hard,Hard,Hard,Clay
draw_size,56.0,8.0,28.0,32.0,48.0,18.0,32.0,28.0
tourney_level,M,A,250,250,M,A,500,250
indoor,I,I,O,O,I,O,O,O
tourney_date,20191028,20251222,20210607,20210719,20181029,20260102,20171002,20250714
match_num,44.0,5.0,4.0,2.0,42.0,1.0,1.0,3.0
winner_id,D875,T0HA,C977,GA36,F324,B0BI,N409,P0CT
winner_seed,NaN,1.0,NaN,NaN,3.0,NaN,1.0,NaN
winner_entry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q
winner_name,Grigor Dimitrov,Learner Tien,Marin Cilic,Emilio Gomez,Roger Federer,Sebastian Baez,Rafael Nadal,Francesco Passaro
winner_hand,R,L,R,R,R,R,L,R
winner_ht,191.0,180.0,198.0,185.0,185.0,170.0,185.0,180.0
winner_ioc,BUL,USA,CRO,ECU,SUI,ARG,ESP,ITA
winner_age,28.452,20.055,32.69,29.64,37.224,25.002,31.332,24.515
winner_rank,27.0,28.0,47.0,168.0,3.0,45.0,1.0,131.0
winner_rank_points,1477.0,1550.0,1388.0,445.0,6260.0,1145.0,9465.0,461.0
loser_id,GD64,L0IL,M0AC,M0AW,N552,MU94,PF39,RC91
loser_seed,NaN,4.0,NaN,NaN,10.0,NaN,NaN,8.0
loser_entry,NaN,NaN,WC,NaN,NaN,NaN,NaN,NaN
loser_name,Cristian Garin,Martin Landaluce,Rudolf Molleker,Nicolas Mejia,Kei Nishikori,Jaume Munar,Lucas Pouille,Arthur Rinderknech
loser_hand,R,R,R,R,R,R,R,R
loser_ht,185.0,193.0,188.0,183.0,178.0,183.0,185.0,196.0
loser_ioc,CHI,ESP,GER,COL,JPN,ESP,FRA,FRA
loser_age,23.411,19.953,20.613,21.435,28.832,28.652,23.606,29.977
loser_rank,42.0,134.0,262.0,301.0,11.0,33.0,23.0,64.0
loser_rank_points,1117.0,455.0,232.0,176.0,3210.0,1385.0,1825.0,923.0
score,6-2 7-5,1-4 4-1 4-3(4) 4-3(2),7-5 6-3,6-4 6-1,6-4 6-4,6-4 6-4,4-6 7-6(6) 7-5,6-1 7-5
best_of,3,5,3,3,3,3,3,3
round,QF,RR,R32,R32,QF,RR,R32,R32
minutes,89.0,91.0,76.0,87.0,79.0,103.0,151.0,74.0
w_ace,6.0,8.0,20.0,8.0,7.0,0.0,4.0,5.0
w_df,3.0,3.0,4.0,3.0,2.0,2.0,7.0,0.0
w_svpt,65.0,65.0,63.0,53.0,56.0,71.0,102.0,51.0
w_1stIn,38.0,42.0,36.0,31.0,29.0,46.0,73.0,37.0
w_1stWon,28.0,33.0,36.0,25.0,28.0,27.0,59.0,30.0
w_2ndWon,14.0,11.0,12.0,12.0,16.0,15.0,15.0,12.0
w_SvGms,10.0,11.0,11.0,8.0,10.0,10.0,17.0,10.0
w_bpSaved,1.0,3.0,5.0,3.0,1.0,4.0,3.0,2.0
w_bpFaced,3.0,5.0,5.0,3.0,1.0,6.0,4.0,2.0
l_ace,1.0,3.0,5.0,3.0,3.0,7.0,9.0,7.0
l_df,2.0,0.0,0.0,3.0,0.0,0.0,5.0,3.0
l_svpt,56.0,69.0,59.0,55.0,63.0,52.0,110.0,49.0
l_1stIn,36.0,47.0,33.0,35.0,37.0,39.0,65.0,26.0
l_1stWon,23.0,39.0,26.0,24.0,21.0,25.0,50.0,22.0
l_2ndWon,7.0,11.0,9.0,6.0,16.0,6.0,21.0,8.0
l_SvGms,10.0,11.0,10.0,9.0,10.0,10.0,17.0,9.0
l_bpSaved,3.0,1.0,0.0,1.0,1.0,2.0,3.0,1.0
l_bpFaced,8.0,3.0,2.0,5.0,3.0,6.0,4.0,4.0

In [7]:
tml_df.to_parquet('./tml.parquet')

In [8]:
# tml_df.sample(4).to_string()

In [9]:
pls_df = pd.read_csv(players_atp_path, encoding='latin1')

In [10]:
pls_df.sample(8).T

,7431,769,1986,2123,1321,389,2770,1025
id,W269,B0RW,D815,E106,C0ID,A172,G654,B960
player,Febi Widhiyanto,Frank Baden,Fabiano De Paula,Jacco Eltingh,Armando Castro,Alejandro Aramburu,Ismar Gorcic,Nick Boyne
atpname,Febi Widhiyanto,Frank Baden,Fabiano De Paula,Jacco Eltingh,Armando Castro,Alejandro Aramburu,Ismar Gorcic,Nick Boyne
birthdate,19800209.0,19390410.0,19881128.0,19700829.0,NaN,19690214.0,19830522.0,NaN
weight,NaN,NaN,78.0,98.0,NaN,64.0,NaN,NaN
height,NaN,NaN,178.0,188.0,NaN,175.0,NaN,NaN
turnedpro,NaN,NaN,NaN,1988.0,NaN,NaN,NaN,NaN
birthplace,NaN,NaN,"Rio De Janeiro, Brazil","Heerde, Netherlands",NaN,"Lima, Peru",NaN,NaN
coaches,NaN,NaN,Duda Matos,Alex Reynders,NaN,NaN,NaN,NaN
hand,R,NaN,R,R,NaN,R,NaN,NaN
backhand,NaN,NaN,1H,NaN,NaN,NaN,NaN,NaN
ioc,INA,LUX,BRA,NED,COL,PER,BIH,NZL

In [11]:
pls_df.to_parquet('./players.parquet')